
[line_break]
disabled = true
[git_branch]
format = "[$branch]($style) "
[java]
format = "[$symbol]($style)"
symbol = "☕"
[nodejs]
format = "[$symbol]($style)"
symbol = " "
[cmd_duration]
format = "[$duration]($style) "
[package]
disabled = true
